language: node_js
node_js:
  - 10
after_success:
  - npm run codecov
before_deploy:
  - npm install
  - npm run docs -- --basename /styled-system
  - cp docs/logo.png docs/logo.svg site
  - touch docs/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master
