language: node_js
node_js:
  - 10
  before_install:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(^(docs|examples))/' || {
        echo "Stopping build process: /docs or /examples changes only."
        exit
      }
install:
  - npm i
  - npm run pkg:prepare
script:
  - npm t
  - npm run pkg:test
after_success:
  - npm run codecov
before_deploy:
  - npm install
  - npm run docs -- --basename /styled-system
  - cp docs/logo.png docs/logo.svg site
  - touch docs/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master
